import Foundation

public typealias MomentID = UUID

/// A factual title. `primary` is the main line ("Kaş"), `secondary` a time label ("August 2025").
public struct MomentTitle: Codable, Hashable, Sendable {
    public var primary: String
    public var secondary: String?

    public init(primary: String, secondary: String? = nil) {
        self.primary = primary
        self.secondary = secondary
    }

    /// "Kaş • August 2025"
    public var combined: String {
        guard let secondary, !secondary.isEmpty else { return primary }
        return "\(primary) • \(secondary)"
    }
}

/// A group of photos/videos that likely belong to the same outing, evening or day.
///
/// Moments are generated by the Memory Engine and can be regenerated at any time. Anything the
/// user adds (notes, hiding, cover choice) lives in `MomentUserState`, keyed by the moment's id.
public struct Moment: Identifiable, Codable, Hashable, Sendable {
    public enum Kind: String, Codable, Hashable, Sendable {
        /// Photos taken close together in time (and usually place).
        case event
        /// Several small moments from the same month, gathered so the timeline isn't a list of singles.
        case collection
        /// Assets without a usable capture date.
        case undated
    }

    public let id: MomentID
    public var kind: Kind
    /// Every member, chronological. Includes collapsed near-duplicates.
    public var assetIDs: [AssetID]
    /// What the moment shows by default, chronological.
    public var featuredAssetIDs: [AssetID]
    /// Near-identical shots and duplicate copies, available behind "Show similar".
    public var similarAssetIDs: [AssetID]
    /// The subset of `similarAssetIDs` that are copies of another asset (e.g. a WhatsApp re-save).
    public var duplicateAssetIDs: [AssetID]
    /// Algorithmic cover choice. A user override lives in `MomentUserState`.
    public var heroAssetID: AssetID?
    public var startDate: Date?
    public var endDate: Date?
    public var centroid: GeoCoordinate?
    public var place: PlaceName?
    public var title: MomentTitle
    public var chapterID: UUID?

    public init(
        id: MomentID,
        kind: Kind,
        assetIDs: [AssetID],
        featuredAssetIDs: [AssetID],
        similarAssetIDs: [AssetID] = [],
        duplicateAssetIDs: [AssetID] = [],
        heroAssetID: AssetID? = nil,
        startDate: Date?,
        endDate: Date?,
        centroid: GeoCoordinate? = nil,
        place: PlaceName? = nil,
        title: MomentTitle = MomentTitle(primary: ""),
        chapterID: UUID? = nil
    ) {
        self.id = id
        self.kind = kind
        self.assetIDs = assetIDs
        self.featuredAssetIDs = featuredAssetIDs
        self.similarAssetIDs = similarAssetIDs
        self.duplicateAssetIDs = duplicateAssetIDs
        self.heroAssetID = heroAssetID
        self.startDate = startDate
        self.endDate = endDate
        self.centroid = centroid
        self.place = place
        self.title = title
        self.chapterID = chapterID
    }

    /// Distinct memories: every member except duplicate copies.
    public var memoryCount: Int { assetIDs.count - duplicateAssetIDs.count }

    /// Used for chronological ordering; undated moments sort last.
    public var sortDate: Date { startDate ?? .distantFuture }
}
